### ISSUE TITLE
High discriminator values at edges

### ISSUE THREAD

**Issue by stefdoerr** [igul222/improved_wgan_training#12]
Hey, I have been trying to make the improved wgan work on my dataset (using the toy examples) but I am getting the weird behaviour that the discriminator learns really high values at the edges of my data space, even though there are close to no samples there.

I don't know if you have any intuition as to what might cause this?
Practically it seems like the generator learns to spawn from the correct distribution but for some reason the discriminator assigns huge values to areas where it hasn't seen any real or fake samples.

![download 1](https://cloud.githubusercontent.com/assets/7935362/25172574/c27182e0-24f1-11e7-98bd-03fc267f1036.png)

![download 2](https://cloud.githubusercontent.com/assets/7935362/25172578/c741735c-24f1-11e7-85a4-9d1e9e5e7cba.png)

**Comment by igul222** [comment]
In theory, the value of the critic at points which are never sampled can be anything at all -- there's no reason to expect those values to remain close to zero. This shouldn't be a problem for learning the generator though, since (as you mention) those points are never actually sampled, so the generator gets no signal from them.
