### ISSUE TITLE
Out Of Memory Error On Gan_Cifar Inception Scoring

### ISSUE THREAD

**Issue by rkjones4** [igul222/improved_wgan_training#13]
Hi I am having an issue where everytime the get_inception_scores() method is called the GPU I am using (GTX 950) runs out of memory. Do you have any suggestions for changes I could make to still see the inception scores? Would it be possible to do this in batches instead of all at once?

**Comment by igul222** [comment]
Definitely should be possible! I've updated the CIFAR10 code to generate images in batches of 100 instead of 1024 (and also fixed a bug in the sampling code). Note that the inception scores that this calculates are on 1000 samples at once; to get scores which are directly comparable to what's typically reported, you want to calculate on 50,000 samples.

**Comment by rkjones4** [comment]
Just as a comment to other people looking at this, finally resolved the issue by forcing the session instantiated by the inception_scoring code to run on the cpu to avoid memory issues
