### ISSUE TITLE
How to interpret the losses?

### ISSUE THREAD

**Issue by wchen342** [igul222/improved_wgan_training#17]
When I tried wgan-gp on my own problems, sometimes I got very unbalanced losses (e.g. the loss of discriminator is high, but the loss of generator is around 0. See [this](https://github.com/wchen342/misc/blob/master/Screenshot_20170426_145419.png)). What does this mean? Does it mean the generator is too good?

**Comment by igul222** [comment]
That's not a problem, your charts look okay. The generator loss is actually meaningless by itself, since the critic's loss is invariant to any constant offset (I.e. A critic F(x) and a critic F(x)+c will perform the same under the critic objective). This means that constant offset will randomly vary up and down (and the generator loss with it). So in general you should pay attention only to the critic loss (actually, the negative of that, if you want your loss curve to look more like the typical supervised curves).

_____________________________

**Comment by wchen342** [comment]
That means sense. Thanks!

**Comment by IPNUISTlegal** [comment]
@igul222 
@wchen342 
![d_loss](https://user-images.githubusercontent.com/35527568/43811657-407c75da-9af0-11e8-91b7-e95a7336d772.png)
![g_loss](https://user-images.githubusercontent.com/35527568/43811658-4134c428-9af0-11e8-84be-1e55ee2e688f.png)
They are WGAN-GP loss function.
I am confused  that the discriminator loss does not convergence to a certain value and crazy up and down swing！
I  am noob in GAN. thx!

**Comment by IronLavender** [comment]
> @igul222
> @wchen342
> 
> 
> They are WGAN-GP loss function.
> I am confused  that the discriminator loss does not convergence to a certain value and crazy up and down swing！
> I  am noob in GAN. thx!

Hello, I am thinking how to draw the loss. Sorry it's a little hard for me because these 2 loss should be seperate and in different loops. Will you share the related code to me? Thank you very much.

**Comment by PGCJ** [comment]
Hello，I am noob in GAN.
I want to konw  that what  looks  normal in WGAN_GP's loss? between Dloss and   Gloss.
