### ISSUE TITLE
How to reproduce ResNet LSUN 128px experiment?

### ISSUE THREAD

**Issue by LIU-Xuanqing** [igul222/improved_wgan_training#30]
Could you please release the code for ResNet generator on LSUN 128px? Thanks!

**Comment by martinarjovsky** [comment]
Hi! The architecture can be found in https://github.com/igul222/nn/blob/master/experiments/wgan/wgan_imagenet128.py . You'll likely need to change the path in https://github.com/igul222/nn/blob/master/tflib/imagenet.py to where the lsun dataset is (here are the images https://s3.amazonaws.com/ishaan-misc/ILSVRC2012_128.tar ).

We'll integrate all to this repo very soon :). Sorry for the delay, some of us are on vacation right now!

Edit: just realized I put out the imagenet images instead of lsun. Here is lsun: https://s3.amazonaws.com/ishaan-misc/lsun_128_train.tar.gz
